import beltSample from "../assets/LandingPage/beltSample.png";
import kurthaSample from "../assets/LandingPage/kuthaSample.png";
import maskSample from "../assets/LandingPage/maskSample.png";
import tshirtSample from "../assets/LandingPage/TshirtSample.png";
import shoesSample from "../assets/LandingPage/shoesSample.png";

export const products = [
  {
    name: "Hemp Twine for Arts and Crafts",
    price: 150,
    image: beltSample,
    category: "Crafts and DIY",
  },
  {
    name: "Organic Cotton and Hemp Blended Sweater",
    price: 700,
    image: tshirtSample,
    category: "Clothing",
  },
  {
    name: "Hemp Masks",
    price: 50,
    image: maskSample,
    category: "Beauty and Wellness",
  },
  {
    name: "Eco-Friendly Hemp Fabric Rolls",
    price: 800,
    image: shoesSample,
    category: "Crafts and DIY",
  },
  {
    name: "Eco-friendly Hemp Belts",
    price: 200,
    image: beltSample,
    category: "Accessories",
  },
  {
    name: "Hemp Throw Blanket",
    price: 900,
    image: shoesSample,
    category: "Home Goods",
  },
  {
    name: "Hemp Wallet",
    price: 180,
    image: shoesSample,
    category: "Accessories",
  },
  {
    name: "Hemp Oil Hair Conditioner",
    price: 400,
    image: tshirtSample,
    category: "Beauty and Wellness",
  },
  {
    name: "Casual Hemp Slip-On Shoes",
    price: 550,
    image: shoesSample,
    category: "Footwear",
  },
  {
    name: "Hemp Scarf with Beautiful Traditional Patterns and Hand-Woven Details",
    price: 150,
    image: tshirtSample,
    category: "Accessories",
  },
  {
    name: "CBD-Infused Hemp Soap Bar",
    price: 250,
    image: beltSample,
    category: "Beauty and Wellness",
  },
  {
    name: "Hemp-Infused Lip Balm",
    price: 120,
    image: beltSample,
    category: "Beauty and Wellness",
  },
  {
    name: "Comfy Hemp Tshirt",
    price: 350,
    image: tshirtSample,
    category: "Clothing",
  },
  {
    name: "Men's Eco-Friendly Hemp Sneakers",
    price: 750,
    image: shoesSample,
    category: "Footwear",
  },
  {
    name: "Handwoven Hemp Hat",
    price: 250,
    image: beltSample,
    category: "Accessories",
  },
  {
    name: "DIY Hemp Macrame Kit",
    price: 700,
    image: shoesSample,
    category: "Crafts and DIY",
  },
  {
    name: "Cannabis Leaf Hoodie with Organic Cotton Blend and Eco-Friendly Dyes",
    price: 480,
    image: shoesSample,
    category: "Clothing",
  },
  {
    name: "Natural Hemp Curtains",
    price: 1500,
    image: tshirtSample,
    category: "Home Goods",
  },
  {
    name: "Handmade Hemp Table Runner",
    price: 500,
    image: tshirtSample,
    category: "Home Goods",
  },
  {
    name: "Cannabis Print Backpack with Multiple Compartments and Adjustable Straps",
    price: 550,
    image: beltSample,
    category: "Accessories",
  },
  {
    name: "Eco friendly Cannabis leaves print outdoor",
    price: 1000,
    image: tshirtSample,
    category: "Clothing",
  },
  {
    name: "Gym Bag Marijuana Leaf of Cannabis Travel",
    price: 600,
    image: shoesSample,
    category: "Accessories",
  },
  {
    name: "Sustainable Hemp Floor Mat",
    price: 1200,
    image: shoesSample,
    category: "Home Goods",
  },
  {
    name: "Natural Hemp Yarn for Knitting and Crocheting",
    price: 450,
    image: beltSample,
    category: "Crafts and DIY",
  },
  {
    name: "Hemp Yoga Pants",
    price: 600,
    image: tshirtSample,
    category: "Clothing",
  },
  {
    name: "Hemp Paper Sketchbook",
    price: 300,
    image: tshirtSample,
    category: "Crafts and DIY",
  },
  {
    name: "High-Top Hemp Skate Sneakers",
    price: 800,
    image: shoesSample,
    category: "Footwear",
  },
  {
    name: "Sustainable Hemp Sunglasses",
    price: 450,
    image: shoesSample,
    category: "Accessories",
  },
  {
    name: "Organic Hemp Bed Sheets",
    price: 2500,
    image: shoesSample,
    category: "Home Goods",
  },
  {
    name: "Hemp Twine for Arts and Crafts",
    price: 150,
    image: beltSample,
    category: "Crafts and DIY",
  },
  {
    name: "Classy Hemp Kurtha",
    price: 350,
    image: kurthaSample,
    category: "Clothing",
  },
  {
    name: "Organic Hemp Essential Oil",
    price: 600,
    image: shoesSample,
    category: "Beauty and Wellness",
  },
  {
    name: "Handwoven Hemp Sandals",
    price: 400,
    image: shoesSample,
    category: "Footwear",
  },
  {
    name: "Eco-Friendly Hemp Pillow Covers",
    price: 300,
    image: beltSample,
    category: "Home Goods",
  },
  {
    name: "Handwoven Hemp Hat",
    price: 250,
    image: beltSample,
    category: "Accessories",
  },
  {
    name: "Men's First Aid Cannabis T-Shirt",
    price: 300,
    image: tshirtSample,
    category: "Clothing",
  },
  {
    name: "Women Men Tennis Shoes Athletic Fashion Green",
    price: 490,
    image: shoesSample,
    category: "Footwear",
  },
  {
    name: "Hemp Twine for Arts and Crafts",
    price: 150,
    image: beltSample,
    category: "Crafts and DIY",
  },
  {
    name: "Organic Cotton and Hemp Blended Sweater",
    price: 700,
    image: tshirtSample,
    category: "Clothing",
  },
  {
    name: "Hemp Masks",
    price: 50,
    image: maskSample,
    category: "Beauty and Wellness",
  },
  {
    name: "Eco-Friendly Hemp Fabric Rolls",
    price: 800,
    image: shoesSample,
    category: "Crafts and DIY",
  },
  {
    name: "Eco-friendly Hemp Belts",
    price: 200,
    image: beltSample,
    category: "Accessories",
  },
  {
    name: "Hemp Throw Blanket",
    price: 900,
    image: shoesSample,
    category: "Home Goods",
  },
  {
    name: "Hemp Wallet",
    price: 180,
    image: shoesSample,
    category: "Accessories",
  },
  {
    name: "Hemp Oil Hair Conditioner",
    price: 400,
    image: tshirtSample,
    category: "Beauty and Wellness",
  },
  {
    name: "Casual Hemp Slip-On Shoes",
    price: 550,
    image: shoesSample,
    category: "Footwear",
  },
  {
    name: "Hemp Scarf with Beautiful Traditional Patterns and Hand-Woven Details",
    price: 150,
    image: tshirtSample,
    category: "Accessories",
  },
  {
    name: "CBD-Infused Hemp Soap Bar",
    price: 250,
    image: beltSample,
    category: "Beauty and Wellness",
  },
  {
    name: "Hemp-Infused Lip Balm",
    price: 120,
    image: beltSample,
    category: "Beauty and Wellness",
  },
  {
    name: "Comfy Hemp Tshirt",
    price: 350,
    image: tshirtSample,
    category: "Clothing",
  },
  {
    name: "Men's Eco-Friendly Hemp Sneakers",
    price: 750,
    image: shoesSample,
    category: "Footwear",
  },
  {
    name: "Handwoven Hemp Hat",
    price: 250,
    image: beltSample,
    category: "Accessories",
  },
  {
    name: "DIY Hemp Macrame Kit",
    price: 700,
    image: shoesSample,
    category: "Crafts and DIY",
  },
  {
    name: "Cannabis Leaf Hoodie with Organic Cotton Blend and Eco-Friendly Dyes",
    price: 480,
    image: shoesSample,
    category: "Clothing",
  },
  {
    name: "Natural Hemp Curtains",
    price: 1500,
    image: tshirtSample,
    category: "Home Goods",
  },
  {
    name: "Handmade Hemp Table Runner",
    price: 500,
    image: tshirtSample,
    category: "Home Goods",
  },
  {
    name: "Cannabis Print Backpack with Multiple Compartments and Adjustable Straps",
    price: 550,
    image: beltSample,
    category: "Accessories",
  },
  {
    name: "Eco friendly Cannabis leaves print outdoor",
    price: 1000,
    image: tshirtSample,
    category: "Clothing",
  },
  {
    name: "Gym Bag Marijuana Leaf of Cannabis Travel",
    price: 600,
    image: shoesSample,
    category: "Accessories",
  },
  {
    name: "Sustainable Hemp Floor Mat",
    price: 1200,
    image: shoesSample,
    category: "Home Goods",
  },
  {
    name: "Natural Hemp Yarn for Knitting and Crocheting",
    price: 450,
    image: beltSample,
    category: "Crafts and DIY",
  },
  {
    name: "Hemp Yoga Pants",
    price: 600,
    image: tshirtSample,
    category: "Clothing",
  },
  {
    name: "Hemp Paper Sketchbook",
    price: 300,
    image: tshirtSample,
    category: "Crafts and DIY",
  },
  {
    name: "High-Top Hemp Skate Sneakers",
    price: 800,
    image: shoesSample,
    category: "Footwear",
  },
  {
    name: "Sustainable Hemp Sunglasses",
    price: 450,
    image: shoesSample,
    category: "Accessories",
  },
  {
    name: "Organic Hemp Bed Sheets",
    price: 2500,
    image: shoesSample,
    category: "Home Goods",
  },
  {
    name: "Hemp Twine for Arts and Crafts",
    price: 150,
    image: beltSample,
    category: "Crafts and DIY",
  },
  {
    name: "Classy Hemp Kurtha",
    price: 350,
    image: kurthaSample,
    category: "Clothing",
  },
  {
    name: "Organic Hemp Essential Oil",
    price: 600,
    image: shoesSample,
    category: "Beauty and Wellness",
  },
  {
    name: "Hemp Twine for Arts and Crafts",
    price: 150,
    image: beltSample,
    category: "Crafts and DIY",
  },
  {
    name: "Organic Cotton and Hemp Blended Sweater",
    price: 700,
    image: tshirtSample,
    category: "Clothing",
  },
  {
    name: "Hemp Masks",
    price: 50,
    image: maskSample,
    category: "Beauty and Wellness",
  },
  {
    name: "Eco-Friendly Hemp Fabric Rolls",
    price: 800,
    image: shoesSample,
    category: "Crafts and DIY",
  },
  {
    name: "Eco-friendly Hemp Belts",
    price: 200,
    image: beltSample,
    category: "Accessories",
  },
  {
    name: "Hemp Throw Blanket",
    price: 900,
    image: shoesSample,
    category: "Home Goods",
  },
  {
    name: "Hemp Wallet",
    price: 180,
    image: shoesSample,
    category: "Accessories",
  },
  {
    name: "Hemp Oil Hair Conditioner",
    price: 400,
    image: tshirtSample,
    category: "Beauty and Wellness",
  },
  {
    name: "Casual Hemp Slip-On Shoes",
    price: 550,
    image: shoesSample,
    category: "Footwear",
  },
  {
    name: "Hemp Scarf with Beautiful Traditional Patterns and Hand-Woven Details",
    price: 150,
    image: tshirtSample,
    category: "Accessories",
  },
  {
    name: "CBD-Infused Hemp Soap Bar",
    price: 250,
    image: beltSample,
    category: "Beauty and Wellness",
  },
  {
    name: "Hemp-Infused Lip Balm",
    price: 120,
    image: beltSample,
    category: "Beauty and Wellness",
  },
  {
    name: "Comfy Hemp Tshirt",
    price: 350,
    image: tshirtSample,
    category: "Clothing",
  },
  {
    name: "Men's Eco-Friendly Hemp Sneakers",
    price: 750,
    image: shoesSample,
    category: "Footwear",
  },
  {
    name: "Handwoven Hemp Hat",
    price: 250,
    image: beltSample,
    category: "Accessories",
  },
  {
    name: "DIY Hemp Macrame Kit",
    price: 700,
    image: shoesSample,
    category: "Crafts and DIY",
  },
  {
    name: "Cannabis Leaf Hoodie with Organic Cotton Blend and Eco-Friendly Dyes",
    price: 480,
    image: shoesSample,
    category: "Clothing",
  },
  {
    name: "Natural Hemp Curtains",
    price: 1500,
    image: tshirtSample,
    category: "Home Goods",
  },
  {
    name: "Handmade Hemp Table Runner",
    price: 500,
    image: tshirtSample,
    category: "Home Goods",
  },
  {
    name: "Cannabis Print Backpack with Multiple Compartments and Adjustable Straps",
    price: 550,
    image: beltSample,
    category: "Accessories",
  },
  {
    name: "Eco friendly Cannabis leaves print outdoor",
    price: 1000,
    image: tshirtSample,
    category: "Clothing",
  },
  {
    name: "Gym Bag Marijuana Leaf of Cannabis Travel",
    price: 600,
    image: shoesSample,
    category: "Accessories",
  },
  {
    name: "Sustainable Hemp Floor Mat",
    price: 1200,
    image: shoesSample,
    category: "Home Goods",
  },
  {
    name: "Natural Hemp Yarn for Knitting and Crocheting",
    price: 450,
    image: beltSample,
    category: "Crafts and DIY",
  },
  {
    name: "Hemp Yoga Pants",
    price: 600,
    image: tshirtSample,
    category: "Clothing",
  },
  {
    name: "Hemp Paper Sketchbook",
    price: 300,
    image: tshirtSample,
    category: "Crafts and DIY",
  },
  {
    name: "High-Top Hemp Skate Sneakers",
    price: 800,
    image: shoesSample,
    category: "Footwear",
  },
  {
    name: "Sustainable Hemp Sunglasses",
    price: 450,
    image: shoesSample,
    category: "Accessories",
  },
  {
    name: "Organic Hemp Bed Sheets",
    price: 2500,
    image: shoesSample,
    category: "Home Goods",
  },
  {
    name: "Hemp Twine for Arts and Crafts",
    price: 150,
    image: beltSample,
    category: "Crafts and DIY",
  },
  {
    name: "Classy Hemp Kurtha",
    price: 350,
    image: kurthaSample,
    category: "Clothing",
  },
  {
    name: "Organic Hemp Essential Oil",
    price: 600,
    image: shoesSample,
    category: "Beauty and Wellness",
  },
  {
    name: "Handwoven Hemp Sandals",
    price: 400,
    image: shoesSample,
    category: "Footwear",
  },
  {
    name: "Eco-Friendly Hemp Pillow Covers",
    price: 300,
    image: beltSample,
    category: "Home Goods",
  },
  {
    name: "Handwoven Hemp Hat",
    price: 250,
    image: beltSample,
    category: "Accessories",
  },
  {
    name: "Men's First Aid Cannabis T-Shirt",
    price: 300,
    image: tshirtSample,
    category: "Clothing",
  },
  {
    name: "Women Men Tennis Shoes Athletic Fashion Green",
    price: 490,
    image: shoesSample,
    category: "Footwear",
  },
  {
    name: "Hemp Twine for Arts and Crafts",
    price: 150,
    image: beltSample,
    category: "Crafts and DIY",
  },
  {
    name: "Organic Cotton and Hemp Blended Sweater",
    price: 700,
    image: tshirtSample,
    category: "Clothing",
  },
  {
    name: "Hemp Masks",
    price: 50,
    image: maskSample,
    category: "Beauty and Wellness",
  },
  {
    name: "Eco-Friendly Hemp Fabric Rolls",
    price: 800,
    image: shoesSample,
    category: "Crafts and DIY",
  },
  {
    name: "Eco-friendly Hemp Belts",
    price: 200,
    image: beltSample,
    category: "Accessories",
  },
  {
    name: "Hemp Throw Blanket",
    price: 900,
    image: shoesSample,
    category: "Home Goods",
  },
  {
    name: "Hemp Wallet",
    price: 180,
    image: shoesSample,
    category: "Accessories",
  },
  {
    name: "Hemp Oil Hair Conditioner",
    price: 400,
    image: tshirtSample,
    category: "Beauty and Wellness",
  },
  {
    name: "Casual Hemp Slip-On Shoes",
    price: 550,
    image: shoesSample,
    category: "Footwear",
  },
  {
    name: "Hemp Scarf with Beautiful Traditional Patterns and Hand-Woven Details",
    price: 150,
    image: tshirtSample,
    category: "Accessories",
  },
  {
    name: "CBD-Infused Hemp Soap Bar",
    price: 250,
    image: beltSample,
    category: "Beauty and Wellness",
  },
  {
    name: "Hemp-Infused Lip Balm",
    price: 120,
    image: beltSample,
    category: "Beauty and Wellness",
  },
  {
    name: "Comfy Hemp Tshirt",
    price: 350,
    image: tshirtSample,
    category: "Clothing",
  },
  {
    name: "Men's Eco-Friendly Hemp Sneakers",
    price: 750,
    image: shoesSample,
    category: "Footwear",
  },
  {
    name: "Handwoven Hemp Hat",
    price: 250,
    image: beltSample,
    category: "Accessories",
  },
  {
    name: "DIY Hemp Macrame Kit",
    price: 700,
    image: shoesSample,
    category: "Crafts and DIY",
  },
  {
    name: "Cannabis Leaf Hoodie with Organic Cotton Blend and Eco-Friendly Dyes",
    price: 480,
    image: shoesSample,
    category: "Clothing",
  },
  {
    name: "Natural Hemp Curtains",
    price: 1500,
    image: tshirtSample,
    category: "Home Goods",
  },
  {
    name: "Handmade Hemp Table Runner",
    price: 500,
    image: tshirtSample,
    category: "Home Goods",
  },
  {
    name: "Cannabis Print Backpack with Multiple Compartments and Adjustable Straps",
    price: 550,
    image: beltSample,
    category: "Accessories",
  },
  {
    name: "Eco friendly Cannabis leaves print outdoor",
    price: 1000,
    image: tshirtSample,
    category: "Clothing",
  },
  {
    name: "Gym Bag Marijuana Leaf of Cannabis Travel",
    price: 600,
    image: shoesSample,
    category: "Accessories",
  },
  {
    name: "Sustainable Hemp Floor Mat",
    price: 1200,
    image: shoesSample,
    category: "Home Goods",
  },
  {
    name: "Natural Hemp Yarn for Knitting and Crocheting",
    price: 450,
    image: beltSample,
    category: "Crafts and DIY",
  },
  {
    name: "Hemp Yoga Pants",
    price: 600,
    image: tshirtSample,
    category: "Clothing",
  },
  {
    name: "Hemp Paper Sketchbook",
    price: 300,
    image: tshirtSample,
    category: "Crafts and DIY",
  },
  {
    name: "High-Top Hemp Skate Sneakers",
    price: 800,
    image: shoesSample,
    category: "Footwear",
  },
  {
    name: "Sustainable Hemp Sunglasses",
    price: 450,
    image: shoesSample,
    category: "Accessories",
  },
  {
    name: "Organic Hemp Bed Sheets",
    price: 2500,
    image: shoesSample,
    category: "Home Goods",
  },
  {
    name: "Hemp Twine for Arts and Crafts",
    price: 150,
    image: beltSample,
    category: "Crafts and DIY",
  },
  {
    name: "Classy Hemp Kurtha",
    price: 350,
    image: kurthaSample,
    category: "Clothing",
  },
  {
    name: "Organic Hemp Essential Oil",
    price: 600,
    image: shoesSample,
    category: "Beauty and Wellness",
  },
];
